language: node_js
sudo: required
dist: trusty
addons:
  apt:
    sources:
      google-chrome
    packages:
      google-chrome-stable
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - export CHROME_BIN=google-chrome
# Rewrite ssh URLs that git uses (for SSH clones in submodules of npm
# dependencies
  - git config --global url."https://".insteadOf git://
